project:
  type: website
  render:
    - "*.qmd"
  resources:
    - CNAME

website:
  title: "Fire Risk"
  navbar:
    left:
      - href: fire/about.qmd
        text: About
      - href: fire/resources.qmd
        text: Resources
      - href: fire/analysis.qmd
        text: Analysis

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
